---
- name: install compiler tools
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present # as long as they are there, it's fine.
  with_items:
    - build-essential
    - automake
    - checkinstall
  become: True
