---
- name: setup leelab monkey exp environment. this is a slim version assuming people would use their own MATLAB...
  hosts: all
  roles:
    # no need for display if people don't use matlab on it...
    #- role: vncserver # this could be useful, since I read somewhere that ggplot2 needs x server.
    #  vncserver_password: zaq1xsw2
    #  vncserver_display: 1
    # they are implicitly required by opencv role.
    #- role: developer
    #- role: developer_python
    #- role: misc
    #- role: matlab
    #  matlab_version: R2012b
    #- role: developer_java
    #- role: protobuf
    - role: opencv